# Generated by Django 4.2 on 2025-01-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('room_number', models.IntegerField(blank=True, null=True)),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('ward', models.CharField(choices=[('Cardiology', 'Cardiology'), ('Rheumatology', 'Rheumatology'), ('Paediatrics', 'Paediatrics'), ('Oncology', 'Oncology'), ('Gastroenterology', 'Gastroenterology'), ('Physiotherapy', 'Physiotherapy'), ('Radiology', 'Radiology')], max_length=50)),
            ],
        ),
    ]
