# Generated by Django 4.2 on 2025-01-27 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_ward'),
        ('wards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='head_of_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wards', to='staff.staff'),
        ),
    ]
