# Generated by Django 4.2 on 2025-01-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Nurse', 'Nurse'), ('Attending Doctor', 'Attending Doctor'), ('Emergency Doctor', 'Emergency Doctor'), ('Head of Department', 'Head of Department'), ('Hospital Manager', 'Hospital Manager')], max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Staff Members',
            },
        ),
    ]
