# Generated by Django 4.2 on 2025-01-27 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0002_staff_ward'),
        ('wards', '0002_ward_head_of_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('Morning Shift', '07:00 - 16:00'), ('Middle Shift', '10:00 - 19:00'), ('Evening Shift', '15:00 - 00:00'), ('Night Shift', '23:00 - 08:00'), ('OnCall Shift', '00:00 - 00:00')], max_length=20)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wards.ward')),
            ],
            options={
                'verbose_name_plural': 'Schedules',
            },
        ),
    ]
