# Generated by Django 4.2 on 2025-01-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='shift',
            field=models.CharField(choices=[('Morning Shift', 'Morning Shift - > 07:00 - 16:00'), ('Middle Shift', 'Middle Shift - > 10:00 - 19:00'), ('Evening Shift', 'Evening Shift - > 15:00 - 00:00'), ('Night Shift', 'Night Shift - > 23:00 - 08:00'), ('OnCall Shift', 'OnCall Shift - > 00:00 - 00:00')], max_length=20),
        ),
    ]
