# Generated by Django 4.2 on 2025-01-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_schedule_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='shift',
            field=models.CharField(choices=[('Morning Shift', 'Morning - 07:00 - 16:00'), ('Middle Shift', 'Middle - 10:00 - 19:00'), ('Evening Shift', 'Evening - 15:00 - 00:00'), ('Night Shift', 'Night - 23:00 - 08:00'), ('OnCall Shift', 'OnCall - 00:00 - 00:00')], max_length=20),
        ),
    ]
